<?php

declare(strict_types=1);

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

/**
 * One-time content seed from fixtures/seed.sql.
 * Generated by pg_dump after inserting data via tinker.
 * Run once on first deploy — do not re-run on existing data.
 */
class ContentSeeder extends Seeder
{
    public function run(): void
    {
        $sql = file_get_contents(database_path('fixtures/seed.sql'));

        if ($sql === false) {
            $this->command->error('fixtures/seed.sql not found');

            return;
        }

        DB::unprepared($sql);

        $this->command->info('Content seeded from fixtures/seed.sql');
    }
}
