/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as FocusedRouteImport } from './routes/_focused'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppThiThuRouteImport } from './routes/_app.thi-thu'
import { Route as AppOverviewRouteImport } from './routes/_app.overview'
import { Route as AppLuyenTapRouteImport } from './routes/_app.luyen-tap'
import { Route as AppKhoaHocRouteImport } from './routes/_app.khoa-hoc'
import { Route as AppThiThuIndexRouteImport } from './routes/_app.thi-thu.index'
import { Route as AppLuyenTapIndexRouteImport } from './routes/_app.luyen-tap.index'
import { Route as AppKhoaHocIndexRouteImport } from './routes/_app.khoa-hoc.index'
import { Route as AppLuyenTapNenTangRouteImport } from './routes/_app.luyen-tap.nen-tang'
import { Route as AppLuyenTapKyNangRouteImport } from './routes/_app.luyen-tap.ky-nang'
import { Route as AppKhoaHocCourseIdRouteImport } from './routes/_app.khoa-hoc.$courseId'
import { Route as FocusedPhongThiExamIdIndexRouteImport } from './routes/_focused.phong-thi.$examId/index'
import { Route as AppThiThuExamIdIndexRouteImport } from './routes/_app.thi-thu.$examId/index'
import { Route as AppLuyenTapNenTangIndexRouteImport } from './routes/_app.luyen-tap.nen-tang.index'
import { Route as AppLuyenTapKyNangIndexRouteImport } from './routes/_app.luyen-tap.ky-nang.index'
import { Route as FocusedPhongThiExamIdKetQuaRouteImport } from './routes/_focused.phong-thi.$examId.ket-qua'
import { Route as FocusedPhongThiExamIdChiTietRouteImport } from './routes/_focused.phong-thi.$examId.chi-tiet'
import { Route as AppLuyenTapNenTangTuVungRouteImport } from './routes/_app.luyen-tap.nen-tang.tu-vung'
import { Route as AppLuyenTapNenTangNguPhapRouteImport } from './routes/_app.luyen-tap.nen-tang.ngu-phap'
import { Route as AppLuyenTapKyNangVietRouteImport } from './routes/_app.luyen-tap.ky-nang.viet'
import { Route as AppLuyenTapKyNangNoiRouteImport } from './routes/_app.luyen-tap.ky-nang.noi'
import { Route as AppLuyenTapKyNangNgheRouteImport } from './routes/_app.luyen-tap.ky-nang.nghe'
import { Route as AppLuyenTapKyNangDocRouteImport } from './routes/_app.luyen-tap.ky-nang.doc'
import { Route as AppLuyenTapNenTangTuVungIndexRouteImport } from './routes/_app.luyen-tap.nen-tang.tu-vung.index'
import { Route as AppLuyenTapNenTangNguPhapIndexRouteImport } from './routes/_app.luyen-tap.nen-tang.ngu-phap.index'
import { Route as AppLuyenTapKyNangVietIndexRouteImport } from './routes/_app.luyen-tap.ky-nang.viet.index'
import { Route as AppLuyenTapKyNangNoiIndexRouteImport } from './routes/_app.luyen-tap.ky-nang.noi.index'
import { Route as AppLuyenTapKyNangNgheIndexRouteImport } from './routes/_app.luyen-tap.ky-nang.nghe.index'
import { Route as AppLuyenTapKyNangDocIndexRouteImport } from './routes/_app.luyen-tap.ky-nang.doc.index'
import { Route as AppLuyenTapNenTangTuVungTopicIdRouteImport } from './routes/_app.luyen-tap.nen-tang.tu-vung.$topicId'
import { Route as AppLuyenTapNenTangNguPhapPointIdIndexRouteImport } from './routes/_app.luyen-tap.nen-tang.ngu-phap.$pointId/index'
import { Route as AppLuyenTapKyNangVietExerciseIdIndexRouteImport } from './routes/_app.luyen-tap.ky-nang.viet.$exerciseId/index'
import { Route as AppLuyenTapKyNangNoiExerciseIdIndexRouteImport } from './routes/_app.luyen-tap.ky-nang.noi.$exerciseId/index'
import { Route as AppLuyenTapKyNangNgheExerciseIdIndexRouteImport } from './routes/_app.luyen-tap.ky-nang.nghe.$exerciseId/index'
import { Route as AppLuyenTapKyNangDocExerciseIdIndexRouteImport } from './routes/_app.luyen-tap.ky-nang.doc.$exerciseId/index'
import { Route as AppLuyenTapKyNangVietExerciseIdKetQuaRouteImport } from './routes/_app.luyen-tap.ky-nang.viet.$exerciseId/ket-qua'
import { Route as AppLuyenTapKyNangNoiExerciseIdKetQuaRouteImport } from './routes/_app.luyen-tap.ky-nang.noi.$exerciseId/ket-qua'
import { Route as AppLuyenTapKyNangVietCauTopicIdIndexRouteImport } from './routes/_app.luyen-tap.ky-nang.viet.cau.$topicId/index'

const FocusedRoute = FocusedRouteImport.update({
  id: '/_focused',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppThiThuRoute = AppThiThuRouteImport.update({
  id: '/thi-thu',
  path: '/thi-thu',
  getParentRoute: () => AppRoute,
} as any)
const AppOverviewRoute = AppOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => AppRoute,
} as any)
const AppLuyenTapRoute = AppLuyenTapRouteImport.update({
  id: '/luyen-tap',
  path: '/luyen-tap',
  getParentRoute: () => AppRoute,
} as any)
const AppKhoaHocRoute = AppKhoaHocRouteImport.update({
  id: '/khoa-hoc',
  path: '/khoa-hoc',
  getParentRoute: () => AppRoute,
} as any)
const AppThiThuIndexRoute = AppThiThuIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppThiThuRoute,
} as any)
const AppLuyenTapIndexRoute = AppLuyenTapIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppLuyenTapRoute,
} as any)
const AppKhoaHocIndexRoute = AppKhoaHocIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppKhoaHocRoute,
} as any)
const AppLuyenTapNenTangRoute = AppLuyenTapNenTangRouteImport.update({
  id: '/nen-tang',
  path: '/nen-tang',
  getParentRoute: () => AppLuyenTapRoute,
} as any)
const AppLuyenTapKyNangRoute = AppLuyenTapKyNangRouteImport.update({
  id: '/ky-nang',
  path: '/ky-nang',
  getParentRoute: () => AppLuyenTapRoute,
} as any)
const AppKhoaHocCourseIdRoute = AppKhoaHocCourseIdRouteImport.update({
  id: '/$courseId',
  path: '/$courseId',
  getParentRoute: () => AppKhoaHocRoute,
} as any)
const FocusedPhongThiExamIdIndexRoute =
  FocusedPhongThiExamIdIndexRouteImport.update({
    id: '/phong-thi/$examId/',
    path: '/phong-thi/$examId/',
    getParentRoute: () => FocusedRoute,
  } as any)
const AppThiThuExamIdIndexRoute = AppThiThuExamIdIndexRouteImport.update({
  id: '/$examId/',
  path: '/$examId/',
  getParentRoute: () => AppThiThuRoute,
} as any)
const AppLuyenTapNenTangIndexRoute = AppLuyenTapNenTangIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppLuyenTapNenTangRoute,
} as any)
const AppLuyenTapKyNangIndexRoute = AppLuyenTapKyNangIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppLuyenTapKyNangRoute,
} as any)
const FocusedPhongThiExamIdKetQuaRoute =
  FocusedPhongThiExamIdKetQuaRouteImport.update({
    id: '/phong-thi/$examId/ket-qua',
    path: '/phong-thi/$examId/ket-qua',
    getParentRoute: () => FocusedRoute,
  } as any)
const FocusedPhongThiExamIdChiTietRoute =
  FocusedPhongThiExamIdChiTietRouteImport.update({
    id: '/phong-thi/$examId/chi-tiet',
    path: '/phong-thi/$examId/chi-tiet',
    getParentRoute: () => FocusedRoute,
  } as any)
const AppLuyenTapNenTangTuVungRoute =
  AppLuyenTapNenTangTuVungRouteImport.update({
    id: '/tu-vung',
    path: '/tu-vung',
    getParentRoute: () => AppLuyenTapNenTangRoute,
  } as any)
const AppLuyenTapNenTangNguPhapRoute =
  AppLuyenTapNenTangNguPhapRouteImport.update({
    id: '/ngu-phap',
    path: '/ngu-phap',
    getParentRoute: () => AppLuyenTapNenTangRoute,
  } as any)
const AppLuyenTapKyNangVietRoute = AppLuyenTapKyNangVietRouteImport.update({
  id: '/viet',
  path: '/viet',
  getParentRoute: () => AppLuyenTapKyNangRoute,
} as any)
const AppLuyenTapKyNangNoiRoute = AppLuyenTapKyNangNoiRouteImport.update({
  id: '/noi',
  path: '/noi',
  getParentRoute: () => AppLuyenTapKyNangRoute,
} as any)
const AppLuyenTapKyNangNgheRoute = AppLuyenTapKyNangNgheRouteImport.update({
  id: '/nghe',
  path: '/nghe',
  getParentRoute: () => AppLuyenTapKyNangRoute,
} as any)
const AppLuyenTapKyNangDocRoute = AppLuyenTapKyNangDocRouteImport.update({
  id: '/doc',
  path: '/doc',
  getParentRoute: () => AppLuyenTapKyNangRoute,
} as any)
const AppLuyenTapNenTangTuVungIndexRoute =
  AppLuyenTapNenTangTuVungIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppLuyenTapNenTangTuVungRoute,
  } as any)
const AppLuyenTapNenTangNguPhapIndexRoute =
  AppLuyenTapNenTangNguPhapIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppLuyenTapNenTangNguPhapRoute,
  } as any)
const AppLuyenTapKyNangVietIndexRoute =
  AppLuyenTapKyNangVietIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppLuyenTapKyNangVietRoute,
  } as any)
const AppLuyenTapKyNangNoiIndexRoute =
  AppLuyenTapKyNangNoiIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppLuyenTapKyNangNoiRoute,
  } as any)
const AppLuyenTapKyNangNgheIndexRoute =
  AppLuyenTapKyNangNgheIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppLuyenTapKyNangNgheRoute,
  } as any)
const AppLuyenTapKyNangDocIndexRoute =
  AppLuyenTapKyNangDocIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppLuyenTapKyNangDocRoute,
  } as any)
const AppLuyenTapNenTangTuVungTopicIdRoute =
  AppLuyenTapNenTangTuVungTopicIdRouteImport.update({
    id: '/$topicId',
    path: '/$topicId',
    getParentRoute: () => AppLuyenTapNenTangTuVungRoute,
  } as any)
const AppLuyenTapNenTangNguPhapPointIdIndexRoute =
  AppLuyenTapNenTangNguPhapPointIdIndexRouteImport.update({
    id: '/$pointId/',
    path: '/$pointId/',
    getParentRoute: () => AppLuyenTapNenTangNguPhapRoute,
  } as any)
const AppLuyenTapKyNangVietExerciseIdIndexRoute =
  AppLuyenTapKyNangVietExerciseIdIndexRouteImport.update({
    id: '/$exerciseId/',
    path: '/$exerciseId/',
    getParentRoute: () => AppLuyenTapKyNangVietRoute,
  } as any)
const AppLuyenTapKyNangNoiExerciseIdIndexRoute =
  AppLuyenTapKyNangNoiExerciseIdIndexRouteImport.update({
    id: '/$exerciseId/',
    path: '/$exerciseId/',
    getParentRoute: () => AppLuyenTapKyNangNoiRoute,
  } as any)
const AppLuyenTapKyNangNgheExerciseIdIndexRoute =
  AppLuyenTapKyNangNgheExerciseIdIndexRouteImport.update({
    id: '/$exerciseId/',
    path: '/$exerciseId/',
    getParentRoute: () => AppLuyenTapKyNangNgheRoute,
  } as any)
const AppLuyenTapKyNangDocExerciseIdIndexRoute =
  AppLuyenTapKyNangDocExerciseIdIndexRouteImport.update({
    id: '/$exerciseId/',
    path: '/$exerciseId/',
    getParentRoute: () => AppLuyenTapKyNangDocRoute,
  } as any)
const AppLuyenTapKyNangVietExerciseIdKetQuaRoute =
  AppLuyenTapKyNangVietExerciseIdKetQuaRouteImport.update({
    id: '/$exerciseId/ket-qua',
    path: '/$exerciseId/ket-qua',
    getParentRoute: () => AppLuyenTapKyNangVietRoute,
  } as any)
const AppLuyenTapKyNangNoiExerciseIdKetQuaRoute =
  AppLuyenTapKyNangNoiExerciseIdKetQuaRouteImport.update({
    id: '/$exerciseId/ket-qua',
    path: '/$exerciseId/ket-qua',
    getParentRoute: () => AppLuyenTapKyNangNoiRoute,
  } as any)
const AppLuyenTapKyNangVietCauTopicIdIndexRoute =
  AppLuyenTapKyNangVietCauTopicIdIndexRouteImport.update({
    id: '/cau/$topicId/',
    path: '/cau/$topicId/',
    getParentRoute: () => AppLuyenTapKyNangVietRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/khoa-hoc': typeof AppKhoaHocRouteWithChildren
  '/luyen-tap': typeof AppLuyenTapRouteWithChildren
  '/overview': typeof AppOverviewRoute
  '/thi-thu': typeof AppThiThuRouteWithChildren
  '/khoa-hoc/$courseId': typeof AppKhoaHocCourseIdRoute
  '/luyen-tap/ky-nang': typeof AppLuyenTapKyNangRouteWithChildren
  '/luyen-tap/nen-tang': typeof AppLuyenTapNenTangRouteWithChildren
  '/khoa-hoc/': typeof AppKhoaHocIndexRoute
  '/luyen-tap/': typeof AppLuyenTapIndexRoute
  '/thi-thu/': typeof AppThiThuIndexRoute
  '/luyen-tap/ky-nang/doc': typeof AppLuyenTapKyNangDocRouteWithChildren
  '/luyen-tap/ky-nang/nghe': typeof AppLuyenTapKyNangNgheRouteWithChildren
  '/luyen-tap/ky-nang/noi': typeof AppLuyenTapKyNangNoiRouteWithChildren
  '/luyen-tap/ky-nang/viet': typeof AppLuyenTapKyNangVietRouteWithChildren
  '/luyen-tap/nen-tang/ngu-phap': typeof AppLuyenTapNenTangNguPhapRouteWithChildren
  '/luyen-tap/nen-tang/tu-vung': typeof AppLuyenTapNenTangTuVungRouteWithChildren
  '/phong-thi/$examId/chi-tiet': typeof FocusedPhongThiExamIdChiTietRoute
  '/phong-thi/$examId/ket-qua': typeof FocusedPhongThiExamIdKetQuaRoute
  '/luyen-tap/ky-nang/': typeof AppLuyenTapKyNangIndexRoute
  '/luyen-tap/nen-tang/': typeof AppLuyenTapNenTangIndexRoute
  '/thi-thu/$examId/': typeof AppThiThuExamIdIndexRoute
  '/phong-thi/$examId/': typeof FocusedPhongThiExamIdIndexRoute
  '/luyen-tap/nen-tang/tu-vung/$topicId': typeof AppLuyenTapNenTangTuVungTopicIdRoute
  '/luyen-tap/ky-nang/doc/': typeof AppLuyenTapKyNangDocIndexRoute
  '/luyen-tap/ky-nang/nghe/': typeof AppLuyenTapKyNangNgheIndexRoute
  '/luyen-tap/ky-nang/noi/': typeof AppLuyenTapKyNangNoiIndexRoute
  '/luyen-tap/ky-nang/viet/': typeof AppLuyenTapKyNangVietIndexRoute
  '/luyen-tap/nen-tang/ngu-phap/': typeof AppLuyenTapNenTangNguPhapIndexRoute
  '/luyen-tap/nen-tang/tu-vung/': typeof AppLuyenTapNenTangTuVungIndexRoute
  '/luyen-tap/ky-nang/noi/$exerciseId/ket-qua': typeof AppLuyenTapKyNangNoiExerciseIdKetQuaRoute
  '/luyen-tap/ky-nang/viet/$exerciseId/ket-qua': typeof AppLuyenTapKyNangVietExerciseIdKetQuaRoute
  '/luyen-tap/ky-nang/doc/$exerciseId/': typeof AppLuyenTapKyNangDocExerciseIdIndexRoute
  '/luyen-tap/ky-nang/nghe/$exerciseId/': typeof AppLuyenTapKyNangNgheExerciseIdIndexRoute
  '/luyen-tap/ky-nang/noi/$exerciseId/': typeof AppLuyenTapKyNangNoiExerciseIdIndexRoute
  '/luyen-tap/ky-nang/viet/$exerciseId/': typeof AppLuyenTapKyNangVietExerciseIdIndexRoute
  '/luyen-tap/nen-tang/ngu-phap/$pointId/': typeof AppLuyenTapNenTangNguPhapPointIdIndexRoute
  '/luyen-tap/ky-nang/viet/cau/$topicId/': typeof AppLuyenTapKyNangVietCauTopicIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/overview': typeof AppOverviewRoute
  '/khoa-hoc/$courseId': typeof AppKhoaHocCourseIdRoute
  '/khoa-hoc': typeof AppKhoaHocIndexRoute
  '/luyen-tap': typeof AppLuyenTapIndexRoute
  '/thi-thu': typeof AppThiThuIndexRoute
  '/phong-thi/$examId/chi-tiet': typeof FocusedPhongThiExamIdChiTietRoute
  '/phong-thi/$examId/ket-qua': typeof FocusedPhongThiExamIdKetQuaRoute
  '/luyen-tap/ky-nang': typeof AppLuyenTapKyNangIndexRoute
  '/luyen-tap/nen-tang': typeof AppLuyenTapNenTangIndexRoute
  '/thi-thu/$examId': typeof AppThiThuExamIdIndexRoute
  '/phong-thi/$examId': typeof FocusedPhongThiExamIdIndexRoute
  '/luyen-tap/nen-tang/tu-vung/$topicId': typeof AppLuyenTapNenTangTuVungTopicIdRoute
  '/luyen-tap/ky-nang/doc': typeof AppLuyenTapKyNangDocIndexRoute
  '/luyen-tap/ky-nang/nghe': typeof AppLuyenTapKyNangNgheIndexRoute
  '/luyen-tap/ky-nang/noi': typeof AppLuyenTapKyNangNoiIndexRoute
  '/luyen-tap/ky-nang/viet': typeof AppLuyenTapKyNangVietIndexRoute
  '/luyen-tap/nen-tang/ngu-phap': typeof AppLuyenTapNenTangNguPhapIndexRoute
  '/luyen-tap/nen-tang/tu-vung': typeof AppLuyenTapNenTangTuVungIndexRoute
  '/luyen-tap/ky-nang/noi/$exerciseId/ket-qua': typeof AppLuyenTapKyNangNoiExerciseIdKetQuaRoute
  '/luyen-tap/ky-nang/viet/$exerciseId/ket-qua': typeof AppLuyenTapKyNangVietExerciseIdKetQuaRoute
  '/luyen-tap/ky-nang/doc/$exerciseId': typeof AppLuyenTapKyNangDocExerciseIdIndexRoute
  '/luyen-tap/ky-nang/nghe/$exerciseId': typeof AppLuyenTapKyNangNgheExerciseIdIndexRoute
  '/luyen-tap/ky-nang/noi/$exerciseId': typeof AppLuyenTapKyNangNoiExerciseIdIndexRoute
  '/luyen-tap/ky-nang/viet/$exerciseId': typeof AppLuyenTapKyNangVietExerciseIdIndexRoute
  '/luyen-tap/nen-tang/ngu-phap/$pointId': typeof AppLuyenTapNenTangNguPhapPointIdIndexRoute
  '/luyen-tap/ky-nang/viet/cau/$topicId': typeof AppLuyenTapKyNangVietCauTopicIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_focused': typeof FocusedRouteWithChildren
  '/_app/khoa-hoc': typeof AppKhoaHocRouteWithChildren
  '/_app/luyen-tap': typeof AppLuyenTapRouteWithChildren
  '/_app/overview': typeof AppOverviewRoute
  '/_app/thi-thu': typeof AppThiThuRouteWithChildren
  '/_app/khoa-hoc/$courseId': typeof AppKhoaHocCourseIdRoute
  '/_app/luyen-tap/ky-nang': typeof AppLuyenTapKyNangRouteWithChildren
  '/_app/luyen-tap/nen-tang': typeof AppLuyenTapNenTangRouteWithChildren
  '/_app/khoa-hoc/': typeof AppKhoaHocIndexRoute
  '/_app/luyen-tap/': typeof AppLuyenTapIndexRoute
  '/_app/thi-thu/': typeof AppThiThuIndexRoute
  '/_app/luyen-tap/ky-nang/doc': typeof AppLuyenTapKyNangDocRouteWithChildren
  '/_app/luyen-tap/ky-nang/nghe': typeof AppLuyenTapKyNangNgheRouteWithChildren
  '/_app/luyen-tap/ky-nang/noi': typeof AppLuyenTapKyNangNoiRouteWithChildren
  '/_app/luyen-tap/ky-nang/viet': typeof AppLuyenTapKyNangVietRouteWithChildren
  '/_app/luyen-tap/nen-tang/ngu-phap': typeof AppLuyenTapNenTangNguPhapRouteWithChildren
  '/_app/luyen-tap/nen-tang/tu-vung': typeof AppLuyenTapNenTangTuVungRouteWithChildren
  '/_focused/phong-thi/$examId/chi-tiet': typeof FocusedPhongThiExamIdChiTietRoute
  '/_focused/phong-thi/$examId/ket-qua': typeof FocusedPhongThiExamIdKetQuaRoute
  '/_app/luyen-tap/ky-nang/': typeof AppLuyenTapKyNangIndexRoute
  '/_app/luyen-tap/nen-tang/': typeof AppLuyenTapNenTangIndexRoute
  '/_app/thi-thu/$examId/': typeof AppThiThuExamIdIndexRoute
  '/_focused/phong-thi/$examId/': typeof FocusedPhongThiExamIdIndexRoute
  '/_app/luyen-tap/nen-tang/tu-vung/$topicId': typeof AppLuyenTapNenTangTuVungTopicIdRoute
  '/_app/luyen-tap/ky-nang/doc/': typeof AppLuyenTapKyNangDocIndexRoute
  '/_app/luyen-tap/ky-nang/nghe/': typeof AppLuyenTapKyNangNgheIndexRoute
  '/_app/luyen-tap/ky-nang/noi/': typeof AppLuyenTapKyNangNoiIndexRoute
  '/_app/luyen-tap/ky-nang/viet/': typeof AppLuyenTapKyNangVietIndexRoute
  '/_app/luyen-tap/nen-tang/ngu-phap/': typeof AppLuyenTapNenTangNguPhapIndexRoute
  '/_app/luyen-tap/nen-tang/tu-vung/': typeof AppLuyenTapNenTangTuVungIndexRoute
  '/_app/luyen-tap/ky-nang/noi/$exerciseId/ket-qua': typeof AppLuyenTapKyNangNoiExerciseIdKetQuaRoute
  '/_app/luyen-tap/ky-nang/viet/$exerciseId/ket-qua': typeof AppLuyenTapKyNangVietExerciseIdKetQuaRoute
  '/_app/luyen-tap/ky-nang/doc/$exerciseId/': typeof AppLuyenTapKyNangDocExerciseIdIndexRoute
  '/_app/luyen-tap/ky-nang/nghe/$exerciseId/': typeof AppLuyenTapKyNangNgheExerciseIdIndexRoute
  '/_app/luyen-tap/ky-nang/noi/$exerciseId/': typeof AppLuyenTapKyNangNoiExerciseIdIndexRoute
  '/_app/luyen-tap/ky-nang/viet/$exerciseId/': typeof AppLuyenTapKyNangVietExerciseIdIndexRoute
  '/_app/luyen-tap/nen-tang/ngu-phap/$pointId/': typeof AppLuyenTapNenTangNguPhapPointIdIndexRoute
  '/_app/luyen-tap/ky-nang/viet/cau/$topicId/': typeof AppLuyenTapKyNangVietCauTopicIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/khoa-hoc'
    | '/luyen-tap'
    | '/overview'
    | '/thi-thu'
    | '/khoa-hoc/$courseId'
    | '/luyen-tap/ky-nang'
    | '/luyen-tap/nen-tang'
    | '/khoa-hoc/'
    | '/luyen-tap/'
    | '/thi-thu/'
    | '/luyen-tap/ky-nang/doc'
    | '/luyen-tap/ky-nang/nghe'
    | '/luyen-tap/ky-nang/noi'
    | '/luyen-tap/ky-nang/viet'
    | '/luyen-tap/nen-tang/ngu-phap'
    | '/luyen-tap/nen-tang/tu-vung'
    | '/phong-thi/$examId/chi-tiet'
    | '/phong-thi/$examId/ket-qua'
    | '/luyen-tap/ky-nang/'
    | '/luyen-tap/nen-tang/'
    | '/thi-thu/$examId/'
    | '/phong-thi/$examId/'
    | '/luyen-tap/nen-tang/tu-vung/$topicId'
    | '/luyen-tap/ky-nang/doc/'
    | '/luyen-tap/ky-nang/nghe/'
    | '/luyen-tap/ky-nang/noi/'
    | '/luyen-tap/ky-nang/viet/'
    | '/luyen-tap/nen-tang/ngu-phap/'
    | '/luyen-tap/nen-tang/tu-vung/'
    | '/luyen-tap/ky-nang/noi/$exerciseId/ket-qua'
    | '/luyen-tap/ky-nang/viet/$exerciseId/ket-qua'
    | '/luyen-tap/ky-nang/doc/$exerciseId/'
    | '/luyen-tap/ky-nang/nghe/$exerciseId/'
    | '/luyen-tap/ky-nang/noi/$exerciseId/'
    | '/luyen-tap/ky-nang/viet/$exerciseId/'
    | '/luyen-tap/nen-tang/ngu-phap/$pointId/'
    | '/luyen-tap/ky-nang/viet/cau/$topicId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/overview'
    | '/khoa-hoc/$courseId'
    | '/khoa-hoc'
    | '/luyen-tap'
    | '/thi-thu'
    | '/phong-thi/$examId/chi-tiet'
    | '/phong-thi/$examId/ket-qua'
    | '/luyen-tap/ky-nang'
    | '/luyen-tap/nen-tang'
    | '/thi-thu/$examId'
    | '/phong-thi/$examId'
    | '/luyen-tap/nen-tang/tu-vung/$topicId'
    | '/luyen-tap/ky-nang/doc'
    | '/luyen-tap/ky-nang/nghe'
    | '/luyen-tap/ky-nang/noi'
    | '/luyen-tap/ky-nang/viet'
    | '/luyen-tap/nen-tang/ngu-phap'
    | '/luyen-tap/nen-tang/tu-vung'
    | '/luyen-tap/ky-nang/noi/$exerciseId/ket-qua'
    | '/luyen-tap/ky-nang/viet/$exerciseId/ket-qua'
    | '/luyen-tap/ky-nang/doc/$exerciseId'
    | '/luyen-tap/ky-nang/nghe/$exerciseId'
    | '/luyen-tap/ky-nang/noi/$exerciseId'
    | '/luyen-tap/ky-nang/viet/$exerciseId'
    | '/luyen-tap/nen-tang/ngu-phap/$pointId'
    | '/luyen-tap/ky-nang/viet/cau/$topicId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_focused'
    | '/_app/khoa-hoc'
    | '/_app/luyen-tap'
    | '/_app/overview'
    | '/_app/thi-thu'
    | '/_app/khoa-hoc/$courseId'
    | '/_app/luyen-tap/ky-nang'
    | '/_app/luyen-tap/nen-tang'
    | '/_app/khoa-hoc/'
    | '/_app/luyen-tap/'
    | '/_app/thi-thu/'
    | '/_app/luyen-tap/ky-nang/doc'
    | '/_app/luyen-tap/ky-nang/nghe'
    | '/_app/luyen-tap/ky-nang/noi'
    | '/_app/luyen-tap/ky-nang/viet'
    | '/_app/luyen-tap/nen-tang/ngu-phap'
    | '/_app/luyen-tap/nen-tang/tu-vung'
    | '/_focused/phong-thi/$examId/chi-tiet'
    | '/_focused/phong-thi/$examId/ket-qua'
    | '/_app/luyen-tap/ky-nang/'
    | '/_app/luyen-tap/nen-tang/'
    | '/_app/thi-thu/$examId/'
    | '/_focused/phong-thi/$examId/'
    | '/_app/luyen-tap/nen-tang/tu-vung/$topicId'
    | '/_app/luyen-tap/ky-nang/doc/'
    | '/_app/luyen-tap/ky-nang/nghe/'
    | '/_app/luyen-tap/ky-nang/noi/'
    | '/_app/luyen-tap/ky-nang/viet/'
    | '/_app/luyen-tap/nen-tang/ngu-phap/'
    | '/_app/luyen-tap/nen-tang/tu-vung/'
    | '/_app/luyen-tap/ky-nang/noi/$exerciseId/ket-qua'
    | '/_app/luyen-tap/ky-nang/viet/$exerciseId/ket-qua'
    | '/_app/luyen-tap/ky-nang/doc/$exerciseId/'
    | '/_app/luyen-tap/ky-nang/nghe/$exerciseId/'
    | '/_app/luyen-tap/ky-nang/noi/$exerciseId/'
    | '/_app/luyen-tap/ky-nang/viet/$exerciseId/'
    | '/_app/luyen-tap/nen-tang/ngu-phap/$pointId/'
    | '/_app/luyen-tap/ky-nang/viet/cau/$topicId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  FocusedRoute: typeof FocusedRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_focused': {
      id: '/_focused'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof FocusedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/thi-thu': {
      id: '/_app/thi-thu'
      path: '/thi-thu'
      fullPath: '/thi-thu'
      preLoaderRoute: typeof AppThiThuRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/overview': {
      id: '/_app/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof AppOverviewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/luyen-tap': {
      id: '/_app/luyen-tap'
      path: '/luyen-tap'
      fullPath: '/luyen-tap'
      preLoaderRoute: typeof AppLuyenTapRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/khoa-hoc': {
      id: '/_app/khoa-hoc'
      path: '/khoa-hoc'
      fullPath: '/khoa-hoc'
      preLoaderRoute: typeof AppKhoaHocRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/thi-thu/': {
      id: '/_app/thi-thu/'
      path: '/'
      fullPath: '/thi-thu/'
      preLoaderRoute: typeof AppThiThuIndexRouteImport
      parentRoute: typeof AppThiThuRoute
    }
    '/_app/luyen-tap/': {
      id: '/_app/luyen-tap/'
      path: '/'
      fullPath: '/luyen-tap/'
      preLoaderRoute: typeof AppLuyenTapIndexRouteImport
      parentRoute: typeof AppLuyenTapRoute
    }
    '/_app/khoa-hoc/': {
      id: '/_app/khoa-hoc/'
      path: '/'
      fullPath: '/khoa-hoc/'
      preLoaderRoute: typeof AppKhoaHocIndexRouteImport
      parentRoute: typeof AppKhoaHocRoute
    }
    '/_app/luyen-tap/nen-tang': {
      id: '/_app/luyen-tap/nen-tang'
      path: '/nen-tang'
      fullPath: '/luyen-tap/nen-tang'
      preLoaderRoute: typeof AppLuyenTapNenTangRouteImport
      parentRoute: typeof AppLuyenTapRoute
    }
    '/_app/luyen-tap/ky-nang': {
      id: '/_app/luyen-tap/ky-nang'
      path: '/ky-nang'
      fullPath: '/luyen-tap/ky-nang'
      preLoaderRoute: typeof AppLuyenTapKyNangRouteImport
      parentRoute: typeof AppLuyenTapRoute
    }
    '/_app/khoa-hoc/$courseId': {
      id: '/_app/khoa-hoc/$courseId'
      path: '/$courseId'
      fullPath: '/khoa-hoc/$courseId'
      preLoaderRoute: typeof AppKhoaHocCourseIdRouteImport
      parentRoute: typeof AppKhoaHocRoute
    }
    '/_focused/phong-thi/$examId/': {
      id: '/_focused/phong-thi/$examId/'
      path: '/phong-thi/$examId'
      fullPath: '/phong-thi/$examId/'
      preLoaderRoute: typeof FocusedPhongThiExamIdIndexRouteImport
      parentRoute: typeof FocusedRoute
    }
    '/_app/thi-thu/$examId/': {
      id: '/_app/thi-thu/$examId/'
      path: '/$examId'
      fullPath: '/thi-thu/$examId/'
      preLoaderRoute: typeof AppThiThuExamIdIndexRouteImport
      parentRoute: typeof AppThiThuRoute
    }
    '/_app/luyen-tap/nen-tang/': {
      id: '/_app/luyen-tap/nen-tang/'
      path: '/'
      fullPath: '/luyen-tap/nen-tang/'
      preLoaderRoute: typeof AppLuyenTapNenTangIndexRouteImport
      parentRoute: typeof AppLuyenTapNenTangRoute
    }
    '/_app/luyen-tap/ky-nang/': {
      id: '/_app/luyen-tap/ky-nang/'
      path: '/'
      fullPath: '/luyen-tap/ky-nang/'
      preLoaderRoute: typeof AppLuyenTapKyNangIndexRouteImport
      parentRoute: typeof AppLuyenTapKyNangRoute
    }
    '/_focused/phong-thi/$examId/ket-qua': {
      id: '/_focused/phong-thi/$examId/ket-qua'
      path: '/phong-thi/$examId/ket-qua'
      fullPath: '/phong-thi/$examId/ket-qua'
      preLoaderRoute: typeof FocusedPhongThiExamIdKetQuaRouteImport
      parentRoute: typeof FocusedRoute
    }
    '/_focused/phong-thi/$examId/chi-tiet': {
      id: '/_focused/phong-thi/$examId/chi-tiet'
      path: '/phong-thi/$examId/chi-tiet'
      fullPath: '/phong-thi/$examId/chi-tiet'
      preLoaderRoute: typeof FocusedPhongThiExamIdChiTietRouteImport
      parentRoute: typeof FocusedRoute
    }
    '/_app/luyen-tap/nen-tang/tu-vung': {
      id: '/_app/luyen-tap/nen-tang/tu-vung'
      path: '/tu-vung'
      fullPath: '/luyen-tap/nen-tang/tu-vung'
      preLoaderRoute: typeof AppLuyenTapNenTangTuVungRouteImport
      parentRoute: typeof AppLuyenTapNenTangRoute
    }
    '/_app/luyen-tap/nen-tang/ngu-phap': {
      id: '/_app/luyen-tap/nen-tang/ngu-phap'
      path: '/ngu-phap'
      fullPath: '/luyen-tap/nen-tang/ngu-phap'
      preLoaderRoute: typeof AppLuyenTapNenTangNguPhapRouteImport
      parentRoute: typeof AppLuyenTapNenTangRoute
    }
    '/_app/luyen-tap/ky-nang/viet': {
      id: '/_app/luyen-tap/ky-nang/viet'
      path: '/viet'
      fullPath: '/luyen-tap/ky-nang/viet'
      preLoaderRoute: typeof AppLuyenTapKyNangVietRouteImport
      parentRoute: typeof AppLuyenTapKyNangRoute
    }
    '/_app/luyen-tap/ky-nang/noi': {
      id: '/_app/luyen-tap/ky-nang/noi'
      path: '/noi'
      fullPath: '/luyen-tap/ky-nang/noi'
      preLoaderRoute: typeof AppLuyenTapKyNangNoiRouteImport
      parentRoute: typeof AppLuyenTapKyNangRoute
    }
    '/_app/luyen-tap/ky-nang/nghe': {
      id: '/_app/luyen-tap/ky-nang/nghe'
      path: '/nghe'
      fullPath: '/luyen-tap/ky-nang/nghe'
      preLoaderRoute: typeof AppLuyenTapKyNangNgheRouteImport
      parentRoute: typeof AppLuyenTapKyNangRoute
    }
    '/_app/luyen-tap/ky-nang/doc': {
      id: '/_app/luyen-tap/ky-nang/doc'
      path: '/doc'
      fullPath: '/luyen-tap/ky-nang/doc'
      preLoaderRoute: typeof AppLuyenTapKyNangDocRouteImport
      parentRoute: typeof AppLuyenTapKyNangRoute
    }
    '/_app/luyen-tap/nen-tang/tu-vung/': {
      id: '/_app/luyen-tap/nen-tang/tu-vung/'
      path: '/'
      fullPath: '/luyen-tap/nen-tang/tu-vung/'
      preLoaderRoute: typeof AppLuyenTapNenTangTuVungIndexRouteImport
      parentRoute: typeof AppLuyenTapNenTangTuVungRoute
    }
    '/_app/luyen-tap/nen-tang/ngu-phap/': {
      id: '/_app/luyen-tap/nen-tang/ngu-phap/'
      path: '/'
      fullPath: '/luyen-tap/nen-tang/ngu-phap/'
      preLoaderRoute: typeof AppLuyenTapNenTangNguPhapIndexRouteImport
      parentRoute: typeof AppLuyenTapNenTangNguPhapRoute
    }
    '/_app/luyen-tap/ky-nang/viet/': {
      id: '/_app/luyen-tap/ky-nang/viet/'
      path: '/'
      fullPath: '/luyen-tap/ky-nang/viet/'
      preLoaderRoute: typeof AppLuyenTapKyNangVietIndexRouteImport
      parentRoute: typeof AppLuyenTapKyNangVietRoute
    }
    '/_app/luyen-tap/ky-nang/noi/': {
      id: '/_app/luyen-tap/ky-nang/noi/'
      path: '/'
      fullPath: '/luyen-tap/ky-nang/noi/'
      preLoaderRoute: typeof AppLuyenTapKyNangNoiIndexRouteImport
      parentRoute: typeof AppLuyenTapKyNangNoiRoute
    }
    '/_app/luyen-tap/ky-nang/nghe/': {
      id: '/_app/luyen-tap/ky-nang/nghe/'
      path: '/'
      fullPath: '/luyen-tap/ky-nang/nghe/'
      preLoaderRoute: typeof AppLuyenTapKyNangNgheIndexRouteImport
      parentRoute: typeof AppLuyenTapKyNangNgheRoute
    }
    '/_app/luyen-tap/ky-nang/doc/': {
      id: '/_app/luyen-tap/ky-nang/doc/'
      path: '/'
      fullPath: '/luyen-tap/ky-nang/doc/'
      preLoaderRoute: typeof AppLuyenTapKyNangDocIndexRouteImport
      parentRoute: typeof AppLuyenTapKyNangDocRoute
    }
    '/_app/luyen-tap/nen-tang/tu-vung/$topicId': {
      id: '/_app/luyen-tap/nen-tang/tu-vung/$topicId'
      path: '/$topicId'
      fullPath: '/luyen-tap/nen-tang/tu-vung/$topicId'
      preLoaderRoute: typeof AppLuyenTapNenTangTuVungTopicIdRouteImport
      parentRoute: typeof AppLuyenTapNenTangTuVungRoute
    }
    '/_app/luyen-tap/nen-tang/ngu-phap/$pointId/': {
      id: '/_app/luyen-tap/nen-tang/ngu-phap/$pointId/'
      path: '/$pointId'
      fullPath: '/luyen-tap/nen-tang/ngu-phap/$pointId/'
      preLoaderRoute: typeof AppLuyenTapNenTangNguPhapPointIdIndexRouteImport
      parentRoute: typeof AppLuyenTapNenTangNguPhapRoute
    }
    '/_app/luyen-tap/ky-nang/viet/$exerciseId/': {
      id: '/_app/luyen-tap/ky-nang/viet/$exerciseId/'
      path: '/$exerciseId'
      fullPath: '/luyen-tap/ky-nang/viet/$exerciseId/'
      preLoaderRoute: typeof AppLuyenTapKyNangVietExerciseIdIndexRouteImport
      parentRoute: typeof AppLuyenTapKyNangVietRoute
    }
    '/_app/luyen-tap/ky-nang/noi/$exerciseId/': {
      id: '/_app/luyen-tap/ky-nang/noi/$exerciseId/'
      path: '/$exerciseId'
      fullPath: '/luyen-tap/ky-nang/noi/$exerciseId/'
      preLoaderRoute: typeof AppLuyenTapKyNangNoiExerciseIdIndexRouteImport
      parentRoute: typeof AppLuyenTapKyNangNoiRoute
    }
    '/_app/luyen-tap/ky-nang/nghe/$exerciseId/': {
      id: '/_app/luyen-tap/ky-nang/nghe/$exerciseId/'
      path: '/$exerciseId'
      fullPath: '/luyen-tap/ky-nang/nghe/$exerciseId/'
      preLoaderRoute: typeof AppLuyenTapKyNangNgheExerciseIdIndexRouteImport
      parentRoute: typeof AppLuyenTapKyNangNgheRoute
    }
    '/_app/luyen-tap/ky-nang/doc/$exerciseId/': {
      id: '/_app/luyen-tap/ky-nang/doc/$exerciseId/'
      path: '/$exerciseId'
      fullPath: '/luyen-tap/ky-nang/doc/$exerciseId/'
      preLoaderRoute: typeof AppLuyenTapKyNangDocExerciseIdIndexRouteImport
      parentRoute: typeof AppLuyenTapKyNangDocRoute
    }
    '/_app/luyen-tap/ky-nang/viet/$exerciseId/ket-qua': {
      id: '/_app/luyen-tap/ky-nang/viet/$exerciseId/ket-qua'
      path: '/$exerciseId/ket-qua'
      fullPath: '/luyen-tap/ky-nang/viet/$exerciseId/ket-qua'
      preLoaderRoute: typeof AppLuyenTapKyNangVietExerciseIdKetQuaRouteImport
      parentRoute: typeof AppLuyenTapKyNangVietRoute
    }
    '/_app/luyen-tap/ky-nang/noi/$exerciseId/ket-qua': {
      id: '/_app/luyen-tap/ky-nang/noi/$exerciseId/ket-qua'
      path: '/$exerciseId/ket-qua'
      fullPath: '/luyen-tap/ky-nang/noi/$exerciseId/ket-qua'
      preLoaderRoute: typeof AppLuyenTapKyNangNoiExerciseIdKetQuaRouteImport
      parentRoute: typeof AppLuyenTapKyNangNoiRoute
    }
    '/_app/luyen-tap/ky-nang/viet/cau/$topicId/': {
      id: '/_app/luyen-tap/ky-nang/viet/cau/$topicId/'
      path: '/cau/$topicId'
      fullPath: '/luyen-tap/ky-nang/viet/cau/$topicId/'
      preLoaderRoute: typeof AppLuyenTapKyNangVietCauTopicIdIndexRouteImport
      parentRoute: typeof AppLuyenTapKyNangVietRoute
    }
  }
}

interface AppKhoaHocRouteChildren {
  AppKhoaHocCourseIdRoute: typeof AppKhoaHocCourseIdRoute
  AppKhoaHocIndexRoute: typeof AppKhoaHocIndexRoute
}

const AppKhoaHocRouteChildren: AppKhoaHocRouteChildren = {
  AppKhoaHocCourseIdRoute: AppKhoaHocCourseIdRoute,
  AppKhoaHocIndexRoute: AppKhoaHocIndexRoute,
}

const AppKhoaHocRouteWithChildren = AppKhoaHocRoute._addFileChildren(
  AppKhoaHocRouteChildren,
)

interface AppLuyenTapKyNangDocRouteChildren {
  AppLuyenTapKyNangDocIndexRoute: typeof AppLuyenTapKyNangDocIndexRoute
  AppLuyenTapKyNangDocExerciseIdIndexRoute: typeof AppLuyenTapKyNangDocExerciseIdIndexRoute
}

const AppLuyenTapKyNangDocRouteChildren: AppLuyenTapKyNangDocRouteChildren = {
  AppLuyenTapKyNangDocIndexRoute: AppLuyenTapKyNangDocIndexRoute,
  AppLuyenTapKyNangDocExerciseIdIndexRoute:
    AppLuyenTapKyNangDocExerciseIdIndexRoute,
}

const AppLuyenTapKyNangDocRouteWithChildren =
  AppLuyenTapKyNangDocRoute._addFileChildren(AppLuyenTapKyNangDocRouteChildren)

interface AppLuyenTapKyNangNgheRouteChildren {
  AppLuyenTapKyNangNgheIndexRoute: typeof AppLuyenTapKyNangNgheIndexRoute
  AppLuyenTapKyNangNgheExerciseIdIndexRoute: typeof AppLuyenTapKyNangNgheExerciseIdIndexRoute
}

const AppLuyenTapKyNangNgheRouteChildren: AppLuyenTapKyNangNgheRouteChildren = {
  AppLuyenTapKyNangNgheIndexRoute: AppLuyenTapKyNangNgheIndexRoute,
  AppLuyenTapKyNangNgheExerciseIdIndexRoute:
    AppLuyenTapKyNangNgheExerciseIdIndexRoute,
}

const AppLuyenTapKyNangNgheRouteWithChildren =
  AppLuyenTapKyNangNgheRoute._addFileChildren(
    AppLuyenTapKyNangNgheRouteChildren,
  )

interface AppLuyenTapKyNangNoiRouteChildren {
  AppLuyenTapKyNangNoiIndexRoute: typeof AppLuyenTapKyNangNoiIndexRoute
  AppLuyenTapKyNangNoiExerciseIdKetQuaRoute: typeof AppLuyenTapKyNangNoiExerciseIdKetQuaRoute
  AppLuyenTapKyNangNoiExerciseIdIndexRoute: typeof AppLuyenTapKyNangNoiExerciseIdIndexRoute
}

const AppLuyenTapKyNangNoiRouteChildren: AppLuyenTapKyNangNoiRouteChildren = {
  AppLuyenTapKyNangNoiIndexRoute: AppLuyenTapKyNangNoiIndexRoute,
  AppLuyenTapKyNangNoiExerciseIdKetQuaRoute:
    AppLuyenTapKyNangNoiExerciseIdKetQuaRoute,
  AppLuyenTapKyNangNoiExerciseIdIndexRoute:
    AppLuyenTapKyNangNoiExerciseIdIndexRoute,
}

const AppLuyenTapKyNangNoiRouteWithChildren =
  AppLuyenTapKyNangNoiRoute._addFileChildren(AppLuyenTapKyNangNoiRouteChildren)

interface AppLuyenTapKyNangVietRouteChildren {
  AppLuyenTapKyNangVietIndexRoute: typeof AppLuyenTapKyNangVietIndexRoute
  AppLuyenTapKyNangVietExerciseIdKetQuaRoute: typeof AppLuyenTapKyNangVietExerciseIdKetQuaRoute
  AppLuyenTapKyNangVietExerciseIdIndexRoute: typeof AppLuyenTapKyNangVietExerciseIdIndexRoute
  AppLuyenTapKyNangVietCauTopicIdIndexRoute: typeof AppLuyenTapKyNangVietCauTopicIdIndexRoute
}

const AppLuyenTapKyNangVietRouteChildren: AppLuyenTapKyNangVietRouteChildren = {
  AppLuyenTapKyNangVietIndexRoute: AppLuyenTapKyNangVietIndexRoute,
  AppLuyenTapKyNangVietExerciseIdKetQuaRoute:
    AppLuyenTapKyNangVietExerciseIdKetQuaRoute,
  AppLuyenTapKyNangVietExerciseIdIndexRoute:
    AppLuyenTapKyNangVietExerciseIdIndexRoute,
  AppLuyenTapKyNangVietCauTopicIdIndexRoute:
    AppLuyenTapKyNangVietCauTopicIdIndexRoute,
}

const AppLuyenTapKyNangVietRouteWithChildren =
  AppLuyenTapKyNangVietRoute._addFileChildren(
    AppLuyenTapKyNangVietRouteChildren,
  )

interface AppLuyenTapKyNangRouteChildren {
  AppLuyenTapKyNangDocRoute: typeof AppLuyenTapKyNangDocRouteWithChildren
  AppLuyenTapKyNangNgheRoute: typeof AppLuyenTapKyNangNgheRouteWithChildren
  AppLuyenTapKyNangNoiRoute: typeof AppLuyenTapKyNangNoiRouteWithChildren
  AppLuyenTapKyNangVietRoute: typeof AppLuyenTapKyNangVietRouteWithChildren
  AppLuyenTapKyNangIndexRoute: typeof AppLuyenTapKyNangIndexRoute
}

const AppLuyenTapKyNangRouteChildren: AppLuyenTapKyNangRouteChildren = {
  AppLuyenTapKyNangDocRoute: AppLuyenTapKyNangDocRouteWithChildren,
  AppLuyenTapKyNangNgheRoute: AppLuyenTapKyNangNgheRouteWithChildren,
  AppLuyenTapKyNangNoiRoute: AppLuyenTapKyNangNoiRouteWithChildren,
  AppLuyenTapKyNangVietRoute: AppLuyenTapKyNangVietRouteWithChildren,
  AppLuyenTapKyNangIndexRoute: AppLuyenTapKyNangIndexRoute,
}

const AppLuyenTapKyNangRouteWithChildren =
  AppLuyenTapKyNangRoute._addFileChildren(AppLuyenTapKyNangRouteChildren)

interface AppLuyenTapNenTangNguPhapRouteChildren {
  AppLuyenTapNenTangNguPhapIndexRoute: typeof AppLuyenTapNenTangNguPhapIndexRoute
  AppLuyenTapNenTangNguPhapPointIdIndexRoute: typeof AppLuyenTapNenTangNguPhapPointIdIndexRoute
}

const AppLuyenTapNenTangNguPhapRouteChildren: AppLuyenTapNenTangNguPhapRouteChildren =
  {
    AppLuyenTapNenTangNguPhapIndexRoute: AppLuyenTapNenTangNguPhapIndexRoute,
    AppLuyenTapNenTangNguPhapPointIdIndexRoute:
      AppLuyenTapNenTangNguPhapPointIdIndexRoute,
  }

const AppLuyenTapNenTangNguPhapRouteWithChildren =
  AppLuyenTapNenTangNguPhapRoute._addFileChildren(
    AppLuyenTapNenTangNguPhapRouteChildren,
  )

interface AppLuyenTapNenTangTuVungRouteChildren {
  AppLuyenTapNenTangTuVungTopicIdRoute: typeof AppLuyenTapNenTangTuVungTopicIdRoute
  AppLuyenTapNenTangTuVungIndexRoute: typeof AppLuyenTapNenTangTuVungIndexRoute
}

const AppLuyenTapNenTangTuVungRouteChildren: AppLuyenTapNenTangTuVungRouteChildren =
  {
    AppLuyenTapNenTangTuVungTopicIdRoute: AppLuyenTapNenTangTuVungTopicIdRoute,
    AppLuyenTapNenTangTuVungIndexRoute: AppLuyenTapNenTangTuVungIndexRoute,
  }

const AppLuyenTapNenTangTuVungRouteWithChildren =
  AppLuyenTapNenTangTuVungRoute._addFileChildren(
    AppLuyenTapNenTangTuVungRouteChildren,
  )

interface AppLuyenTapNenTangRouteChildren {
  AppLuyenTapNenTangNguPhapRoute: typeof AppLuyenTapNenTangNguPhapRouteWithChildren
  AppLuyenTapNenTangTuVungRoute: typeof AppLuyenTapNenTangTuVungRouteWithChildren
  AppLuyenTapNenTangIndexRoute: typeof AppLuyenTapNenTangIndexRoute
}

const AppLuyenTapNenTangRouteChildren: AppLuyenTapNenTangRouteChildren = {
  AppLuyenTapNenTangNguPhapRoute: AppLuyenTapNenTangNguPhapRouteWithChildren,
  AppLuyenTapNenTangTuVungRoute: AppLuyenTapNenTangTuVungRouteWithChildren,
  AppLuyenTapNenTangIndexRoute: AppLuyenTapNenTangIndexRoute,
}

const AppLuyenTapNenTangRouteWithChildren =
  AppLuyenTapNenTangRoute._addFileChildren(AppLuyenTapNenTangRouteChildren)

interface AppLuyenTapRouteChildren {
  AppLuyenTapKyNangRoute: typeof AppLuyenTapKyNangRouteWithChildren
  AppLuyenTapNenTangRoute: typeof AppLuyenTapNenTangRouteWithChildren
  AppLuyenTapIndexRoute: typeof AppLuyenTapIndexRoute
}

const AppLuyenTapRouteChildren: AppLuyenTapRouteChildren = {
  AppLuyenTapKyNangRoute: AppLuyenTapKyNangRouteWithChildren,
  AppLuyenTapNenTangRoute: AppLuyenTapNenTangRouteWithChildren,
  AppLuyenTapIndexRoute: AppLuyenTapIndexRoute,
}

const AppLuyenTapRouteWithChildren = AppLuyenTapRoute._addFileChildren(
  AppLuyenTapRouteChildren,
)

interface AppThiThuRouteChildren {
  AppThiThuIndexRoute: typeof AppThiThuIndexRoute
  AppThiThuExamIdIndexRoute: typeof AppThiThuExamIdIndexRoute
}

const AppThiThuRouteChildren: AppThiThuRouteChildren = {
  AppThiThuIndexRoute: AppThiThuIndexRoute,
  AppThiThuExamIdIndexRoute: AppThiThuExamIdIndexRoute,
}

const AppThiThuRouteWithChildren = AppThiThuRoute._addFileChildren(
  AppThiThuRouteChildren,
)

interface AppRouteChildren {
  AppKhoaHocRoute: typeof AppKhoaHocRouteWithChildren
  AppLuyenTapRoute: typeof AppLuyenTapRouteWithChildren
  AppOverviewRoute: typeof AppOverviewRoute
  AppThiThuRoute: typeof AppThiThuRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppKhoaHocRoute: AppKhoaHocRouteWithChildren,
  AppLuyenTapRoute: AppLuyenTapRouteWithChildren,
  AppOverviewRoute: AppOverviewRoute,
  AppThiThuRoute: AppThiThuRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface FocusedRouteChildren {
  FocusedPhongThiExamIdChiTietRoute: typeof FocusedPhongThiExamIdChiTietRoute
  FocusedPhongThiExamIdKetQuaRoute: typeof FocusedPhongThiExamIdKetQuaRoute
  FocusedPhongThiExamIdIndexRoute: typeof FocusedPhongThiExamIdIndexRoute
}

const FocusedRouteChildren: FocusedRouteChildren = {
  FocusedPhongThiExamIdChiTietRoute: FocusedPhongThiExamIdChiTietRoute,
  FocusedPhongThiExamIdKetQuaRoute: FocusedPhongThiExamIdKetQuaRoute,
  FocusedPhongThiExamIdIndexRoute: FocusedPhongThiExamIdIndexRoute,
}

const FocusedRouteWithChildren =
  FocusedRoute._addFileChildren(FocusedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  FocusedRoute: FocusedRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
