<?php

declare(strict_types=1);

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

return new class extends Migration
{
    public function up(): void
    {
        $now = now();

        DB::table('practice_speaking_scenarios')->insert([
            // A1
            [
                'id' => Str::uuid()->toString(),
                'slug' => 'introducing-your-family',
                'title' => 'Introducing your family',
                'level' => 'A1',
                'character_name' => 'Anna',
                'character_voice_label' => 'us Sierra',
                'description' => 'Anna is your new classmate. She wants to know about your family. Tell her about your parents, siblings, and what they do.',
                'system_prompt' => 'You are Anna, a curious and friendly classmate. Ask simple questions about the user\'s family members, their names, ages, and jobs. Keep language at A1 level. React warmly to answers.',
                'opening_line' => 'Hi! I would love to know more about you. Can you tell me about your family?',
                'target_vocab' => json_encode(['My father is', 'My mother works', 'I have a brother']),
                'estimated_minutes' => 4,
                'expected_turns' => 5,
                'is_published' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => Str::uuid()->toString(),
                'slug' => 'talking-about-hobbies',
                'title' => 'Talking about hobbies',
                'level' => 'A1',
                'character_name' => 'Ben',
                'character_voice_label' => 'us Adam',
                'description' => 'Ben is your neighbor. You meet at the park and talk about what you like to do in your free time.',
                'system_prompt' => 'You are Ben, a friendly neighbor who loves outdoor activities. Ask about hobbies, sports, and free time. Keep language at A1 level. Share your own hobbies briefly.',
                'opening_line' => 'Hey there! Nice day for a walk, right? What do you usually do on weekends?',
                'target_vocab' => json_encode(['I like to', 'In my free time', 'How about you']),
                'estimated_minutes' => 4,
                'expected_turns' => 5,
                'is_published' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            // A2
            [
                'id' => Str::uuid()->toString(),
                'slug' => 'ordering-food-at-restaurant',
                'title' => 'Ordering food at a restaurant',
                'level' => 'A2',
                'character_name' => 'Sophie',
                'character_voice_label' => 'us Sierra',
                'description' => 'Sophie is a waitress at a Vietnamese restaurant. Order your meal, ask about ingredients, and request the bill.',
                'system_prompt' => 'You are Sophie, a cheerful waitress at a restaurant. Help guests with the menu, describe dishes simply, take orders, and bring the bill. Keep language at A2 level.',
                'opening_line' => 'Good evening! Welcome to Golden Lotus. Here is the menu. Are you ready to order?',
                'target_vocab' => json_encode(['I would like to have', 'What do you recommend', 'Can I have the bill']),
                'estimated_minutes' => 5,
                'expected_turns' => 6,
                'is_published' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => Str::uuid()->toString(),
                'slug' => 'buying-a-bus-ticket',
                'title' => 'Buying a bus ticket',
                'level' => 'A2',
                'character_name' => 'Kevin',
                'character_voice_label' => 'us Adam',
                'description' => 'Kevin works at the bus station. You need to buy a ticket, ask about schedules, and find the right platform.',
                'system_prompt' => 'You are Kevin, a helpful bus station clerk. Help passengers with ticket purchases, schedules, platforms, and travel times. Keep language at A2 level. Be patient.',
                'opening_line' => 'Hello! Welcome to the central bus station. Where would you like to go?',
                'target_vocab' => json_encode(['How much is', 'What time does', 'Which platform']),
                'estimated_minutes' => 5,
                'expected_turns' => 6,
                'is_published' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            // B1
            [
                'id' => Str::uuid()->toString(),
                'slug' => 'discussing-healthy-lifestyle',
                'title' => 'Discussing a healthy lifestyle',
                'level' => 'B1',
                'character_name' => 'Coach Ryan',
                'character_voice_label' => 'us Adam',
                'description' => 'Coach Ryan is a fitness trainer. Discuss exercise habits, diet, and ways to stay healthy. Ask for advice on improving your lifestyle.',
                'system_prompt' => 'You are Coach Ryan, an encouraging fitness trainer. Discuss exercise routines, healthy eating, sleep habits, and stress management. Give practical advice. Keep language at B1 level.',
                'opening_line' => 'Hey! Great to see you at the gym. How has your health routine been lately?',
                'target_vocab' => json_encode(['I have been trying to', 'Do you think I should', 'What would you suggest']),
                'estimated_minutes' => 7,
                'expected_turns' => 7,
                'is_published' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => Str::uuid()->toString(),
                'slug' => 'solving-a-school-problem',
                'title' => 'Solving a school problem',
                'level' => 'B1',
                'character_name' => 'Ms. Chen',
                'character_voice_label' => 'us Sierra',
                'description' => 'Ms. Chen is your academic advisor. You are struggling with time management and study-life balance. Discuss the problem and find solutions together.',
                'system_prompt' => 'You are Ms. Chen, a supportive academic advisor. Listen to student problems, ask clarifying questions, and suggest practical solutions for time management and study habits. Keep language at B1 level.',
                'opening_line' => 'Hello! Thanks for coming to see me. You mentioned you have been feeling overwhelmed. What is going on?',
                'target_vocab' => json_encode(['The problem is', 'I think we could', 'One solution might be']),
                'estimated_minutes' => 7,
                'expected_turns' => 7,
                'is_published' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => Str::uuid()->toString(),
                'slug' => 'planning-a-birthday-party',
                'title' => 'Planning a birthday party',
                'level' => 'B1',
                'character_name' => 'Lisa',
                'character_voice_label' => 'us Sierra',
                'description' => 'Lisa is your close friend. Together you are planning a surprise birthday party for a mutual friend. Discuss the venue, food, decorations, and guest list.',
                'system_prompt' => 'You are Lisa, an enthusiastic friend planning a surprise party. Discuss logistics, make suggestions, and compromise on ideas. Keep language at B1 level. Be excited and collaborative.',
                'opening_line' => "Hey! So we need to plan something amazing for Sarah's birthday next week. Have you thought of any ideas?",
                'target_vocab' => json_encode(['How about we', 'That sounds great but', 'We should also consider']),
                'estimated_minutes' => 6,
                'expected_turns' => 7,
                'is_published' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            // B2
            [
                'id' => Str::uuid()->toString(),
                'slug' => 'debating-social-media-impact',
                'title' => 'Debating social media impact',
                'level' => 'B2',
                'character_name' => 'Professor Lee',
                'character_voice_label' => 'us Adam',
                'description' => 'Professor Lee is leading a class discussion about the impact of social media on young people. Share your opinions, give examples, and respond to counterarguments.',
                'system_prompt' => 'You are Professor Lee, a university lecturer facilitating a debate. Present balanced views, challenge student opinions constructively, and ask for evidence. Use natural B2-level English with academic vocabulary.',
                'opening_line' => 'Today we are discussing social media and its effects on young people. What is your overall view — do you think social media does more harm or good?',
                'target_vocab' => json_encode(['On the one hand', 'Research has shown that', 'I would argue that']),
                'estimated_minutes' => 8,
                'expected_turns' => 8,
                'is_published' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => Str::uuid()->toString(),
                'slug' => 'discussing-education-system',
                'title' => 'Discussing the education system',
                'level' => 'B2',
                'character_name' => 'Karen',
                'character_voice_label' => 'us Sierra',
                'description' => 'Karen is a fellow student from another country. Compare education systems, discuss strengths and weaknesses, and share ideas for improvement.',
                'system_prompt' => 'You are Karen, an international exchange student interested in comparing education systems. Share your experience, ask thoughtful questions, and engage in nuanced discussion. Use natural B2-level English.',
                'opening_line' => 'I have been studying here for a semester now and I have noticed some interesting differences from my country. How do you feel about the education system here?',
                'target_vocab' => json_encode(['Compared to', 'The advantage of', 'In my experience']),
                'estimated_minutes' => 8,
                'expected_turns' => 8,
                'is_published' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => Str::uuid()->toString(),
                'slug' => 'environmental-solutions',
                'title' => 'Proposing environmental solutions',
                'level' => 'B2',
                'character_name' => 'Daniel',
                'character_voice_label' => 'us Adam',
                'description' => 'Daniel is an environmental activist. Discuss pollution, climate change, and propose practical solutions for your community.',
                'system_prompt' => 'You are Daniel, a passionate environmental activist. Discuss specific environmental problems, evaluate proposed solutions, and brainstorm practical actions. Use natural B2-level English with topic-specific vocabulary.',
                'opening_line' => 'Thanks for joining our community meeting. We are looking for practical ideas to make our neighborhood more eco-friendly. What environmental issues concern you the most?',
                'target_vocab' => json_encode(['The main issue is', 'We could address this by', 'It is essential that']),
                'estimated_minutes' => 8,
                'expected_turns' => 8,
                'is_published' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ]);
    }

    public function down(): void
    {
        DB::table('practice_speaking_scenarios')
            ->whereIn('slug', [
                'introducing-your-family',
                'talking-about-hobbies',
                'ordering-food-at-restaurant',
                'buying-a-bus-ticket',
                'discussing-healthy-lifestyle',
                'solving-a-school-problem',
                'planning-a-birthday-party',
                'debating-social-media-impact',
                'discussing-education-system',
                'environmental-solutions',
            ])
            ->delete();
    }
};
